_wandb:
    value:
        cli_version: 0.24.1
        e:
            gzbukc2r1crvdgboomc2i5gcrftdt7vw:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: origin_patchTST.py
                codePathLocal: origin_patchTST.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "215558234112"
                email: suuuuwimmer@gmail.com
                executable: /Users/suyeong/miniconda3/envs/pydev310/bin/python
                git:
                    commit: 7c94227b6029a82e1115886b0a10610944ae046f
                    remote: https://github.com/swimmerRAt/influenza-prediction-model.git
                host: Mac.local
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/suyeong/Desktop/temp_workspace/influenza-prediction-model/origin_patchTST.py
                python: CPython 3.10.14
                root: /Users/suyeong/Desktop/temp_workspace/influenza-prediction-model
                startedAt: "2026-02-04T06:42:19.347674Z"
                writerId: gzbukc2r1crvdgboomc2i5gcrftdt7vw
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 13
                - 16
            "4": 3.10.14
            "5": 0.24.1
            "8":
                - 2
            "12": 0.24.1
            "13": darwin-arm64
affine:
    value: 1
batch_size:
    value: 128
c_out:
    value: 10
checkpoints:
    value: ./checkpoints/
d_ff:
    value: 256
d_layers:
    value: 1
d_model:
    value: 128
data:
    value: influenza
data_path:
    value: merged_influenza_data.csv
dec_in:
    value: 10
decomposition:
    value: 0
des:
    value: Exp
device_ids:
    value:
        - 0
devices:
    value: 0,1,2,3
dropout:
    value: 0.2
e_layers:
    value: 3
embed:
    value: timeF
enc_in:
    value: 10
fc_dropout:
    value: 0.2
features:
    value: MS
freq:
    value: w
gpu:
    value: 0
head_dropout:
    value: 0
individual:
    value: 0
is_training:
    value: 1
kernel_size:
    value: 25
label_len:
    value: 48
learning_rate:
    value: 0.0001
loss:
    value: mse
lradj:
    value: TST
model:
    value: PatchTST
model_id:
    value: Influenza_PatchTST
n_heads:
    value: 16
num_workers:
    value: 0
output_attention:
    value: false
padding_patch:
    value: end
patch_len:
    value: 7
patience:
    value: 20
pct_start:
    value: 0.4
pred_len:
    value: 31
random_seed:
    value: null
revin:
    value: 1
root_path:
    value: .
seq_len:
    value: 365
stride:
    value: 3
subtract_last:
    value: 0
target:
    value: ili
train_epochs:
    value: 10
use_amp:
    value: false
use_gpu:
    value: false
use_multi_gpu:
    value: false
