_wandb:
    value:
        cli_version: 0.24.1
        e:
            751e6nryxk0zqcehbr7oi9tfi6juwb9m:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: patchTST.py
                codePathLocal: patchTST.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "206864363520"
                email: suuuuwimmer@gmail.com
                executable: /Users/suyeong/miniconda3/envs/pydev310/bin/python
                git:
                    commit: 7d804794212d494a03d10d4377017c285a9e254f
                    remote: https://github.com/swimmerRAt/influenza-prediction-model.git
                host: Mac.local
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/suyeong/Desktop/temp_workspace/influenza-prediction-model/patchTST.py
                python: CPython 3.10.14
                root: /Users/suyeong/Desktop/temp_workspace/influenza-prediction-model
                startedAt: "2026-02-16T11:53:56.737152Z"
                writerId: 751e6nryxk0zqcehbr7oi9tfi6juwb9m
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.14
            "5": 0.24.1
            "8":
                - 2
            "12": 0.24.1
            "13": darwin-arm64
amp_weight:
    value: 0.02
batch_size:
    value: 32
d_model:
    value: 64
dropout:
    value: 0.2
enc_layers:
    value: 3
epochs:
    value: 200
ff_dim:
    value: 64
head_hidden:
    value:
        - 64
        - 32
loss:
    value: amplitude_aware_mse
loss_type:
    value: amp+slope
lr:
    value: 0.0003
n_heads:
    value: 4
patch_len:
    value: 4
pred_len:
    value: 3
recon_w_end:
    value: 0.5
recon_w_start:
    value: 2
scaler_type:
    value: standard
seq_len:
    value: 26
slope_weight:
    value: 0.1
stride:
    value: 1
tanh_alpha:
    value: 8
tanh_gain:
    value: 6
tanh_learnable:
    value: true
weight_decay:
    value: 0.005
